name: Lint and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          pip install -r requirements.txt
          pip install .
      - name: Install locales
        run: |
          apt-get update
          apt-get -y install locales
          locale-gen en_US
          locale-gen de_DE
          locale-gen fr_FR
          locale-gen en_US
          locale-gen es_ES
          locale-gen it_IT
          locale-gen nl_NL
          locale-gen cs_CZ
          locale -a
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest
