name: Lint and Test

on: [push, pull_request, workflow_dispatch]

jobs:
  lint_and_test:
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.9
      - run: |
          pip install -r requirements.txt
          pip install .
      - name: Install locales
        run: |
          sudo apt update
          sudo apt -y install locales
          sudo locale-gen en_US.UTF-8
          sudo locale-gen de_DE.UTF-8
          sudo locale-gen fr_FR.UTF-8
          sudo locale-gen en_US.UTF-8
          sudo locale-gen es_ES.UTF-8
          sudo locale-gen it_IT.UTF-8
          sudo locale-gen nl_NL.UTF-8
          sudo locale-gen cs_CZ.UTF-8
      - name: Lint
        run: pre-commit run --all-files
      - name: Test
        run: pytest
